name: Build and Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  docker:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Actions.Docker.Web/Dockerfile --tag docker.web:$(date +%s)
